site_name: Synonyms in Quran
site_description: "A comparision of synonyms in Quran."
site_url: "https://nqcm.github.io/synonyms-in-quran"
site_author: "Naveera Ashraf"

copyright: "© All rights reserved - naveeraashraf.com"

repo_name: "nqcm/synonyms-in-quran"
repo_url: "https://github.com/nqcm/synonyms-in-quran"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nqcm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/niqabicodermum
    - icon: fontawesome/brands/linkedin
      link: https://za.linkedin.com/in/naveera-ashraf
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/niqabi.coder.mum/


theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: cyan
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: cyan

  logo: material/library
  favicon: img/logo.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.share

  plugins:
    - social
    - search:
      lang:
        - eng
        - ar
        
