site_name: Synonyms in Quran
site_description: "A comparision of synonyms in Quran."
site_url: "https://nqcm.github.io/synonyms-in-quran"
site_author: "Naveera Ashraf"

copyright: "© All rights reserved - naveeraashraf.com"

repo_name: "nqcm/synonyms-in-quran"
repo_url: "https://github.com/nqcm/synonyms-in-quran"

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nqcm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/niqabicodermum
    - icon: fontawesome/brands/linkedin
      link: https://za.linkedin.com/in/naveera-ashraf
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/niqabi.coder.mum/

nav:
  - Home: index.md
  - Alphabetical Index: index/index.md
  - Sources: index/sources.md
  - Synonymy in Arabic language: index/synonymy.md

theme:
  name: material
  annotation: material/arrow-right-circle
  palette:
    - scheme: slate
      primary: teal
      accent: teal

  logo: img/logo.png
  favicon: img/logo.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.share

  plugins:
    - social
    - search:
      lang:
        - eng
        - ar
